### ISSUE TITLE
running drake-iiwa-driver without drake

### ISSUE THREAD

**Issue by TheCamusean** [RobotLocomotion/drake-iiwa-driver#28]
Hi,

Your driver seems quite nice, but would it be possible running it without drake?

I would like to have as less dependencies as possible.

**Comment by jwnimmer-tri** [comment]
Currently, this driver is using https://github.com/RobotLocomotion/drake/blob/master/lcmtypes/lcmt_iiwa_status.lcm and https://github.com/RobotLocomotion/drake/blob/master/lcmtypes/lcmt_iiwa_command.lcm message from Drake, so no.

Perhaps we should relocate those messages to https://github.com/RobotLocomotion/lcmtypes instead, and then we could drop the dependency on Drake.  What do you think, @sammy-tri or others?

In the meantime, @TheCamusean you could do something similar your own fork of this project, if you need it immediately.

**Comment by TheCamusean** [comment]
Okey, I modified the LCMClient and become it in ROSClient, now it has direct communication with ROS.

Anyway, seems sometimes is doing shaking movements to reach the goal. Was it also happening to you?

**Comment by peteflorence** [comment]
Hi Julen, one cause of shaking we have experienced is if the driver is not
able to publish messages at high enough rate because, for example, the
overall system CPU is bogged down with other processes. The best way to
solve that issue was to keep the CPU plenty not-overloaded, even by running
less processes or buying a processor with more cores. It also seemed to
help to the up the priority of the process which runs the driver.

You might have many other reasons for your shakiness though. Not sure what
your control stack is like.

Also if you look at the “master-rlg” branch we also have a ROSClient there.

Good luck with your robot!

**Comment by sammy-tri** [comment]
> Perhaps we should relocate those messages to https://github.com/RobotLocomotion/lcmtypes instead, and then we could drop the dependency on Drake. What do you think, @sammy-tri or others?

https://github.com/RobotLocomotion/drake/issues/7045 has some discussion of where to locate the lcmtypes as well

Closing this issue as the LCM dependency is being tracked in drake and there's currently no plan to make this a ROS based driver.
