### ISSUE TITLE
URDF model for torque control

### ISSUE THREAD

**Issue by TheCamusean** [RobotLocomotion/drake-iiwa-driver#30]
Hi,

I have seen that you are using FRI also so do torque control of the robot.

I was wondering if you have a dynamic model of the robot. masses, CoM, inertia matrix in order to control better.

Best,

Julen U.

**Comment by sammy-tri** [comment]
I've been mostly using the robot in position control mode, so I don't have a lot of experience with the torque control behavior.  Drake's models of the iiwa live here https://github.com/RobotLocomotion/drake/tree/master/manipulation/models/iiwa_description but I can't personally vouch for the accuracy of the dynamics in the model (since I haven't actually used these models for torque control of the arm).
